export const events = [
  {
    image: "/images/event1.png",
    title: "Google I/O 2026",
    slug: "google-io-2026",
    location: "Mountain View, CA, USA",
    date: "May 20, 2026",
    time: "9:00 AM PDT",
  },
  {
    image: "/images/event2.png",
    title: "Microsoft Build 2026",
    slug: "microsoft-build-2026",
    location: "Seattle, WA, USA",
    date: "May 27, 2026",
    time: "10:00 AM PDT",
  },
  {
    image: "/images/event3.png",
    title: "AWS re:Invent 2026",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV, USA",
    date: "Dec 1, 2026",
    time: "8:30 AM PST",
  },
  {
    image: "/images/event4.png",
    title: "JSConf Budapest 2026",
    slug: "jsconf-budapest-2026",
    location: "Budapest, Hungary",
    date: "Sep 24, 2026",
    time: "9:30 AM CEST",
  },
  {
    image: "/images/event5.png",
    title: "ETHGlobal Hackathon: London 2026",
    slug: "ethglobal-london-2026",
    location: "London, UK",
    date: "Jul 17, 2026",
    time: "6:00 PM BST",
  },
  {
    image: "/images/event6.png",
    title: "React Summit 2026",
    slug: "react-summit-2026",
    location: "Amsterdam, Netherlands",
    date: "Jun 12, 2026",
    time: "9:00 AM CEST",
  },
];
