export const events = [
  {
    image: "/images/event1.png",
    title: "Addis Tech Week 2026",
    slug: "addis-tech-week-2026",
    location: "Millennium Hall, Addis Ababa, Ethiopia",
    date: "May 22, 2026",
    time: "9:00 AM EAT",
  },
  {
    image: "/images/event2.png",
    title: "Addis Web & Mobile Meetup",
    slug: "addis-web-mobile-meetup",
    location: "Iceaddis, Bole, Addis Ababa",
    date: "Jun 6, 2026",
    time: "5:30 PM EAT",
  },
  {
    image: "/images/event3.png",
    title: "Ethiopia AI & Data Conference",
    slug: "ethiopia-ai-data-conference-2026",
    location: "Skylight Hotel Conference Center, Addis Ababa",
    date: "Jul 11, 2026",
    time: "10:00 AM EAT",
  },
  {
    image: "/images/event4.png",
    title: "Addis JS Community Night",
    slug: "addis-js-community-night",
    location: "xHub Addis, Kazanchis, Addis Ababa",
    date: "Aug 14, 2026",
    time: "6:00 PM EAT",
  },
  {
    image: "/images/event5.png",
    title: "Sheba Valley Hackathon 2026",
    slug: "sheba-valley-hackathon-2026",
    location: "ECA Conference Center, Addis Ababa",
    date: "Sep 18, 2026",
    time: "8:30 AM EAT",
  },
  {
    image: "/images/event6.png",
    title: "Addis DevOps & Cloud Summit",
    slug: "addis-devops-cloud-summit-2026",
    location: "Hyatt Regency, Meskel Square, Addis Ababa",
    date: "Oct 3, 2026",
    time: "9:30 AM EAT",
  },
];
